import { z } from 'zod'

export const newSurveySchema = z.object({
  role: z.enum(['estudiante_computacion', 'profesional_tecnico', 'no_tecnico', 'otro']),
  roleOther: z.string().trim().max(150).optional(),
  device: z.enum(['laptop_desktop', 'telefono', 'tablet']),
  familiarity: z.enum(['no_conocia', 'solo_nombre', 'conocimiento_general', 'conocimiento_alto']),
  homeOfferSummary: z.string().trim().min(2).max(500),
  homeValueClarity: z.number().int().min(1).max(5),
  homeNextStepClarity: z.number().int().min(1).max(5),
  homeNextAction: z.enum(['registrarme_login', 'ver_recursos', 'ver_eventos', 'explorar_comunidad', 'no_supe']),
  suggestedPathScore: z.number().int().min(1).max(5),
  suggestedPathImprove: z.string().trim().max(500).optional(),
  firstPublicRoute: z.enum(['eventos', 'recursos', 'oportunidades', 'noticias', 'nosotros']),
  routeUtilityScore: z.number().int().min(1).max(5),
  routeTrustScore: z.number().int().min(1).max(5),
  missingTrust: z.string().trim().max(600).optional(),
  registerProbability: z.number().int().min(1).max(5),
  registerBarrier: z.enum([
    'no_valor_suficiente',
    'no_entendi_beneficios',
    'no_tengo_tiempo',
    'desconfianza',
    'otro',
  ]),
  registerMotivator: z.enum(['tutorias', 'mentorias', 'eventos', 'recursos_curados', 'networking', 'otro']),
  topNewUserImprovement: z.string().trim().min(2).max(600),
  commonValueClarity: z.number().int().min(1).max(5),
  commonSiteUtility: z.number().int().min(1).max(5),
  commonRecommendProbability: z.number().int().min(1).max(5),
  commonMostValuableModule: z.string().trim().min(2).max(200),
  commonPriorityImprovement: z.string().trim().min(2).max(600),
})

export const returningSurveySchema = z.object({
  overallComparedToPrevious: z.enum(['mucho_mejor', 'mejor', 'igual', 'peor']),
  mostImprovedArea: z.enum([
    'claridad_mensaje',
    'navegacion',
    'diseno_visual',
    'rendimiento_responsive',
    'sin_cambios',
  ]),
  pendingAspect: z.string().trim().min(2).max(600),
  testedLoginRegister: z.boolean(),
  loginEase: z.number().int().min(1).max(5).optional(),
  loginOutcome: z.enum(['completado', 'parcial', 'no_completado']).optional(),
  testedOnboarding: z.boolean(),
  onboardingProgressClarity: z.number().int().min(1).max(5).optional(),
  onboardingMainFriction: z.enum([
    'no_entendi_que_hacer',
    'flujo_largo',
    'problemas_tecnicos',
    'falta_valor_percibido',
    'otro',
  ]).optional(),
  usedCommunityHub: z.boolean(),
  mainCommunityModule: z.enum(['ideas', 'tutorias', 'mentores', 'beneficios']).optional(),
  completedCommunityAction: z.enum([
    'crear_idea',
    'votar_idea',
    'solicitar_tutoria',
    'revisar_mentores',
    'ninguna',
  ]).optional(),
  communityNextStepClarity: z.number().int().min(1).max(5).optional(),
  mainCommunityBlocker: z.enum([
    'falta_tiempo',
    'no_entendi_siguiente_paso',
    'poco_contenido_actividad',
    'no_vi_beneficio',
    'otro',
  ]).optional(),
  visitedContentRoutes: z.array(z.enum(['eventos', 'recursos', 'oportunidades', 'noticias'])).min(1),
  returnMostMotivatingRoute: z.enum(['eventos', 'recursos', 'oportunidades', 'noticias']),
  completedValueAction: z.enum(['si', 'parcial', 'no']),
  weeklyReturnProbability: z.number().int().min(1).max(5),
  topThreeSprintImprovements: z.array(
    z.enum([
      'simplificar_home',
      'mejorar_onboarding',
      'mejorar_perfil_hub',
      'mas_actividad_comunidad',
      'mejorar_eventos_conversion',
      'mejorar_recursos_oportunidades',
      'mejoras_mobile_responsive',
    ]),
  ).min(1).max(3),
  poFirstChange: z.string().trim().min(2).max(700),
  commonValueClarity: z.number().int().min(1).max(5),
  commonSiteUtility: z.number().int().min(1).max(5),
  commonRecommendProbability: z.number().int().min(1).max(5),
  commonMostValuableModule: z.string().trim().min(2).max(200),
  commonPriorityImprovement: z.string().trim().min(2).max(600),
})

export type NewSurveyInput = z.infer<typeof newSurveySchema>
export type ReturningSurveyInput = z.infer<typeof returningSurveySchema>
